# Generated by Django 6.0 on 2025-12-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.IntegerField(default=2002),
        ),
    ]
