# Generated by Django 6.0 on 2025-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_department_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.CharField(default='it@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
